function [averageFitnessEachStep] = generateFitnessAgainstPopulationSize(populationSizeRange, ...
                                                 trialsPerStep, ...
                                                 generations, ...
                                                 projectionHeight, ...
                                                 projectionWidth, ...
                                                 initialMutationSparsity, ...
                                                 finalMutationSparsity, ...
                                                 decayFactor, ...
                                                 transmissionMatrix)

% --- code use to generate plot for noise against varying population size
    colIndex = 1;
    fitness = zeros(trialsPerStep, length(populationSizeRange));
    for projections = populationSizeRange 
        for trial = 1:trialsPerStep
           bestProjection = geneticAlgorithm(generations, ...
                                             projections, ...
                                             projectionHeight, ...
                                             projectionWidth, ...
                                             initialMutationSparsity, ...
                                             finalMutationSparsity, ...
                                             decayFactor, ...
                                             transmissionMatrix);

           fitness(trial, colIndex) = bestProjection.cost;
        end
        colIndex = colIndex + 1;
    end
    averageFitnessEachStep = mean(fitness);
end